# Generated by Django 5.1.3 on 2024-12-12 16:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0004_comment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='reated_at',
            new_name='created_at',
        ),
    ]
